import { reactive } from 'vue';

export const inquiryEmail = '1378554398@qq.com';

// 新手只需要改这里和下面 products/categoryGroups：
// 1. 图片放到 public/电子烟 文件夹。
// 2. 路径写成 /电子烟/图片文件名.jpg。
// 3. 菜单层级改 categoryGroups，商品归类改 product.category。
export const heroSlides = [
  {
    image: '/电子烟/placeholders/pod-slim.svg',
    title: 'Wholesale vape catalogue',
    titleZh: '批发电子烟产品目录',
  },
  {
    image: '/电子烟/placeholders/disposable-max.svg',
    title: 'Device and pod systems',
    titleZh: '设备与烟弹系统',
  },
  {
    image: '/电子烟/placeholders/packaging-suite.svg',
    title: 'Packaging and OEM support',
    titleZh: '包装与 OEM 支持',
  },
];

export const store = reactive({
  language: localStorage.getItem('language') || 'en',
  theme: localStorage.getItem('theme') || 'system',

  setLanguage(newLanguage) {
    this.language = newLanguage === 'zh' ? 'zh' : 'en';
    localStorage.setItem('language', this.language);
  },

  setTheme(newTheme) {
    this.theme = newTheme;
    localStorage.setItem('theme', newTheme);
  },

  categoryGroups: [
    {
      id: 'devices',
      name: 'Devices',
      nameZh: '设备系列',
      description: 'Core vape hardware families for wholesale catalogues and brand programs.',
      descriptionZh: '面向批发目录和品牌项目的核心电子烟硬件系列。',
      children: [
        {
          id: 'pod-systems',
          name: 'Pod Systems',
          nameZh: '换弹设备',
          shortName: 'Pods',
          shortNameZh: '换弹',
          description: 'Compact refillable and replaceable pod devices for distributors and private-label programs.',
          descriptionZh: '适合经销商和贴牌项目的紧凑型可注油/可换弹设备。',
          heroImage: '/电子烟/placeholders/pod-slim.svg',
        },
        {
          id: 'starter-kits',
          name: 'Starter Kits',
          nameZh: '套装产品',
          shortName: 'Kits',
          shortNameZh: '套装',
          description:
            'Bundled device and packaging solutions built for brand launches, channel samples, and wholesale catalogues.',
          descriptionZh: '适合品牌首发、渠道样品和批发目录的设备与包装套装。',
          heroImage: '/电子烟/placeholders/starter-kit-box.svg',
        },
      ],
    },
    {
      id: 'ready-lines',
      name: 'Ready Lines',
      nameZh: '现成系列',
      description: 'Fast catalogue items for distributors that need clear SKUs and quick quotation.',
      descriptionZh: '适合需要清晰 SKU 和快速报价的经销商目录产品。',
      children: [
        {
          id: 'disposable-vapes',
          name: 'Disposable Vapes',
          nameZh: '一次性电子烟',
          shortName: 'Disposables',
          shortNameZh: '一次性',
          description:
            'Ready-to-ship disposable lines with modern finishes, multiple capacity tiers, and market-ready packaging.',
          descriptionZh: '具备现代外观、多容量档位和市场化包装的一次性产品线。',
          heroImage: '/电子烟/placeholders/disposable-max.svg',
        },
        {
          id: 'sample-packs',
          name: 'Sample Packs',
          nameZh: '样品套包',
          shortName: 'Samples',
          shortNameZh: '样品',
          description: 'Mixed samples for buyer evaluation, trade-show preparation, and distributor sales teams.',
          descriptionZh: '用于买家评估、展会准备和经销商销售团队的混合样品包。',
          heroImage: '/电子烟/placeholders/sample-pack.svg',
        },
      ],
    },
    {
      id: 'parts-accessories',
      name: 'Parts & Accessories',
      nameZh: '配件与耗材',
      description: 'Replacement parts and add-on items for repeat orders, service packs, and channel replenishment.',
      descriptionZh: '用于复购订单、售后套包和渠道补货的替换件与附加产品。',
      children: [
        {
          id: 'replacement-pods',
          name: 'Replacement Pods',
          nameZh: '替换烟弹',
          shortName: 'Pods',
          shortNameZh: '烟弹',
          description: 'Replacement cartridges and pod packs for repeat-purchase programs and distributor replenishment.',
          descriptionZh: '面向复购项目和经销商补货的替换烟弹与烟弹套包。',
          heroImage: '/电子烟/placeholders/replacement-pods.svg',
        },
        {
          id: 'coils-accessories',
          name: 'Coils & Accessories',
          nameZh: '雾化芯与配件',
          shortName: 'Coils',
          shortNameZh: '雾化芯',
          description: 'Mesh coils, cables, lanyards, and small accessories that support catalogue follow-up orders.',
          descriptionZh: 'Mesh 雾化芯、线材、挂绳和小配件，适合目录后续补充订单。',
          heroImage: '/电子烟/placeholders/coil-pack.svg',
        },
      ],
    },
    {
      id: 'brand-support',
      name: 'Brand Support',
      nameZh: '品牌支持',
      description: 'Packaging and OEM services that turn selected models into market-ready business orders.',
      descriptionZh: '把选定型号转化为可上市商业订单的包装与 OEM 服务。',
      children: [
        {
          id: 'packaging-oem',
          name: 'Packaging & OEM',
          nameZh: '包装与 OEM',
          shortName: 'OEM',
          shortNameZh: 'OEM',
          description: 'Retail boxes, sleeves, manuals, logo placement, and sample-ready presentation support.',
          descriptionZh: '支持零售盒、套筒、说明书、Logo 位置和样品展示包装。',
          heroImage: '/电子烟/placeholders/packaging-suite.svg',
        },
        {
          id: 'retail-displays',
          name: 'Retail Displays',
          nameZh: '陈列物料',
          shortName: 'Displays',
          shortNameZh: '陈列',
          description: 'Counter displays, sample boards, and sales tools for distributors and retail channel teams.',
          descriptionZh: '面向经销商和零售渠道团队的柜台陈列、样品板和销售工具。',
          heroImage: '/电子烟/placeholders/display-stand.svg',
        },
      ],
    },
  ],

  get categories() {
    return this.categoryGroups.flatMap((group) => group.children);
  },

  get representativeProducts() {
    return this.categoryGroups
      .map((group) => {
        const categoryIds = group.children.map((category) => category.id);
        const product = this.products.find((item) => categoryIds.includes(item.category));
        return product ? { group, product } : null;
      })
      .filter(Boolean);
  },

  products: [
    {
      id: 1,
      name: 'Aurora Slim Pod',
      image: '/电子烟/placeholders/pod-slim.svg',
      category: 'pod-systems',
      description:
        'A slim aluminum pod device for channel-ready nicotine salt programs. The clean shell, stable draw activation, and lightweight format make it easy to position for everyday retail.',
      descriptionZh: '轻薄铝合金换弹设备，适合渠道型尼古丁盐项目。外壳干净、吸阻稳定、机身轻巧，方便放入日常零售目录。',
      highlights: ['Refillable 2 ml pod', 'Draw-activated output', 'Logo and shell color options'],
      highlightsZh: ['2 ml 可注油烟弹', '吸气启动输出', '支持 Logo 和外壳颜色定制'],
      specs: [
        { label: 'Battery', value: '450 mAh' },
        { label: 'Pod Capacity', value: '2 ml' },
        { label: 'Material', value: 'Aluminum alloy body' },
        { label: 'MOQ', value: '500 pcs per color' },
      ],
      specsZh: [
        { label: '电池', value: '450 mAh' },
        { label: '烟弹容量', value: '2 ml' },
        { label: '材质', value: '铝合金机身' },
        { label: '起订量', value: '每色 500 件' },
      ],
      moq: '500 pcs',
      moqZh: '500 件',
      leadTime: '7-15 days',
      leadTimeZh: '7-15 天',
      badge: 'OEM Ready',
      badgeZh: '支持 OEM',
    },
    {
      id: 2,
      name: 'Nova Ceramic Pod',
      image: '/电子烟/placeholders/pod-ceramic.svg',
      category: 'pod-systems',
      description:
        'A refillable ceramic-core pod solution focused on smoother flavor delivery and repeat-purchase cartridge programs for wholesale buyers.',
      descriptionZh: '可注油陶瓷芯换弹方案，面向批发买家的顺滑口感和复购烟弹项目。',
      highlights: ['Ceramic coil option', 'Magnetic pod connection', 'Leak-resistant structure'],
      highlightsZh: ['可选陶瓷芯', '磁吸烟弹连接', '防漏结构'],
      specs: [
        { label: 'Battery', value: '520 mAh' },
        { label: 'Resistance', value: '1.0 ohm / 1.2 ohm' },
        { label: 'Charging', value: 'USB-C' },
        { label: 'MOQ', value: '800 pcs' },
      ],
      specsZh: [
        { label: '电池', value: '520 mAh' },
        { label: '阻值', value: '1.0 ohm / 1.2 ohm' },
        { label: '充电', value: 'USB-C' },
        { label: '起订量', value: '800 件' },
      ],
      moq: '800 pcs',
      moqZh: '800 件',
      leadTime: '10-18 days',
      leadTimeZh: '10-18 天',
      badge: 'Stable Supply',
      badgeZh: '稳定供货',
    },
    {
      id: 3,
      name: 'Pulse Max Disposable',
      image: '/电子烟/placeholders/disposable-max.svg',
      category: 'disposable-vapes',
      description:
        'A high-capacity disposable vape line for distributors who need strong shelf presence, consistent vapor output, and fast SKU rollout.',
      descriptionZh: '高容量一次性电子烟系列，适合需要货架识别度、稳定出雾和快速 SKU 上新的经销商。',
      highlights: ['Large e-liquid capacity tier', 'Mesh coil configuration', 'Flavor and packaging customization'],
      highlightsZh: ['大容量油仓档位', 'Mesh 网芯配置', '支持口味与包装定制'],
      specs: [
        { label: 'Puffs', value: 'Up to 8000' },
        { label: 'Coil', value: 'Mesh coil' },
        { label: 'Battery', value: 'Rechargeable option' },
        { label: 'MOQ', value: '1000 pcs per flavor' },
      ],
      specsZh: [
        { label: '口数', value: '最高 8000 口' },
        { label: '雾化芯', value: 'Mesh 网芯' },
        { label: '电池', value: '可选可充电方案' },
        { label: '起订量', value: '每口味 1000 件' },
      ],
      moq: '1000 pcs',
      moqZh: '1000 件',
      leadTime: '12-20 days',
      leadTimeZh: '12-20 天',
      badge: 'Distributor Pick',
      badgeZh: '经销商优选',
    },
    {
      id: 4,
      name: 'Edge Mini Disposable',
      image: '/电子烟/placeholders/disposable-mini.svg',
      category: 'disposable-vapes',
      description:
        'A compact disposable product for sample packs, convenience channels, and markets that prefer a smaller device footprint.',
      descriptionZh: '小尺寸一次性产品，适合样品包、便利渠道，以及偏好小机身的市场。',
      highlights: ['Pocket-size shell', 'Smooth matte finish', 'Retail box support'],
      highlightsZh: ['口袋尺寸外壳', '顺滑磨砂表面', '支持零售包装盒'],
      specs: [
        { label: 'Puffs', value: 'Up to 3000' },
        { label: 'Activation', value: 'Auto draw' },
        { label: 'Finish', value: 'Matte / gradient' },
        { label: 'MOQ', value: '1000 pcs' },
      ],
      specsZh: [
        { label: '口数', value: '最高 3000 口' },
        { label: '启动方式', value: '自动吸气启动' },
        { label: '表面工艺', value: '磨砂 / 渐变' },
        { label: '起订量', value: '1000 件' },
      ],
      moq: '1000 pcs',
      moqZh: '1000 件',
      leadTime: '10-16 days',
      leadTimeZh: '10-16 天',
      badge: 'Fast Turnaround',
      badgeZh: '快速交付',
    },
    {
      id: 5,
      name: 'Launch Kit Box Set',
      image: '/电子烟/placeholders/starter-kit-box.svg',
      category: 'starter-kits',
      description:
        'A complete starter kit package for brands preparing trade-show samples, distributor onboarding, or first retail placement.',
      descriptionZh: '完整套装包装方案，适合品牌准备展会样品、经销商首批上架或首次零售铺货。',
      highlights: ['Device, pod, cable, and manual bundle', 'Custom insert and sleeve', 'Barcode and compliance label area'],
      highlightsZh: ['设备、烟弹、线材和说明书组合', '支持定制内托与套筒', '预留条码和合规标签区域'],
      specs: [
        { label: 'Packaging', value: 'Rigid box / sleeve' },
        { label: 'Insert', value: 'Paper tray or EVA option' },
        { label: 'Branding', value: 'Logo, color, manual' },
        { label: 'MOQ', value: '500 sets' },
      ],
      specsZh: [
        { label: '包装', value: '硬盒 / 套筒' },
        { label: '内托', value: '纸托或 EVA 可选' },
        { label: '品牌定制', value: 'Logo、颜色、说明书' },
        { label: '起订量', value: '500 套' },
      ],
      moq: '500 sets',
      moqZh: '500 套',
      leadTime: '15-25 days',
      leadTimeZh: '15-25 天',
      badge: 'Private Label',
      badgeZh: '贴牌方案',
    },
    {
      id: 6,
      name: 'Display Sample Pack',
      image: '/电子烟/placeholders/sample-pack.svg',
      category: 'sample-packs',
      description:
        'A curated sample pack for buyers comparing finishes, flavors, and device families before confirming a wholesale order.',
      descriptionZh: '组合样品包，方便买家在确认批发订单前比较表面工艺、口味和设备系列。',
      highlights: ['Mixed models in one pack', 'Finish and color comparison', 'Useful for sales teams'],
      highlightsZh: ['多型号组合样品', '便于比较工艺和颜色', '适合销售团队展示'],
      specs: [
        { label: 'Pack Type', value: 'Mixed SKU sample set' },
        { label: 'Use Case', value: 'Buyer evaluation' },
        { label: 'Branding', value: 'Neutral or branded' },
        { label: 'MOQ', value: 'By inquiry' },
      ],
      specsZh: [
        { label: '套包类型', value: '混合 SKU 样品组' },
        { label: '使用场景', value: '买家评估' },
        { label: '品牌方式', value: '中性或品牌化' },
        { label: '起订量', value: '询盘确认' },
      ],
      moq: 'By inquiry',
      moqZh: '询盘确认',
      leadTime: '3-7 days',
      leadTimeZh: '3-7 天',
      badge: 'Sample Friendly',
      badgeZh: '样品友好',
    },
    {
      id: 7,
      name: 'Metro Open Pod Kit',
      image: '/电子烟/placeholders/open-pod-kit.svg',
      category: 'starter-kits',
      description:
        'A starter kit configuration for first-order brand launches, built around a compact device, clear inserts, and retail-ready documentation.',
      descriptionZh: '首批品牌发布用套装配置，围绕紧凑设备、清晰内托和零售化说明资料搭建。',
      highlights: ['Starter device bundle', 'Manual and cable included', 'Ready for branded sleeve'],
      highlightsZh: ['入门设备套装', '包含说明书和线材', '可配品牌套筒'],
      specs: [
        { label: 'Kit Type', value: 'Device + pod + cable' },
        { label: 'Packaging', value: 'Window box / sleeve' },
        { label: 'Branding', value: 'Color and logo options' },
        { label: 'MOQ', value: '600 sets' },
      ],
      specsZh: [
        { label: '套装类型', value: '设备 + 烟弹 + 线材' },
        { label: '包装', value: '开窗盒 / 套筒' },
        { label: '品牌定制', value: '颜色和 Logo 可选' },
        { label: '起订量', value: '600 套' },
      ],
      moq: '600 sets',
      moqZh: '600 套',
      leadTime: '14-22 days',
      leadTimeZh: '14-22 天',
      badge: 'Kit Program',
      badgeZh: '套装项目',
    },
    {
      id: 8,
      name: 'Cloud Bar Pro',
      image: '/电子烟/placeholders/disposable-bar.svg',
      category: 'disposable-vapes',
      description:
        'A disposable vape format for buyers who need stronger shelf visibility, consistent hand feel, and multiple flavor rollout potential.',
      descriptionZh: '一次性产品形态，适合需要更强货架表现、稳定手感和多口味铺货能力的买家。',
      highlights: ['Rounded ergonomic shell', 'Rechargeable battery option', 'Multi-flavor carton support'],
      highlightsZh: ['圆润人体工学外壳', '可选可充电电池', '支持多口味外箱方案'],
      specs: [
        { label: 'Puffs', value: 'Up to 6000' },
        { label: 'Charging', value: 'USB-C option' },
        { label: 'Coil', value: 'Mesh' },
        { label: 'MOQ', value: '1000 pcs per flavor' },
      ],
      specsZh: [
        { label: '口数', value: '最高 6000 口' },
        { label: '充电', value: '可选 USB-C' },
        { label: '雾化芯', value: 'Mesh' },
        { label: '起订量', value: '每口味 1000 件' },
      ],
      moq: '1000 pcs',
      moqZh: '1000 件',
      leadTime: '12-18 days',
      leadTimeZh: '12-18 天',
      badge: 'Retail Ready',
      badgeZh: '零售就绪',
    },
    {
      id: 9,
      name: 'OEM Packaging Suite',
      image: '/电子烟/placeholders/packaging-suite.svg',
      category: 'packaging-oem',
      description:
        'Packaging coordination for selected catalogue items, including box structure, sleeve design, barcode area, and sales sample presentation.',
      descriptionZh: '为目录产品提供包装协同，包括盒型结构、套筒设计、条码区域和销售样品展示。',
      highlights: ['Retail box layout support', 'Manual and insert options', 'Sample-ready presentation'],
      highlightsZh: ['支持零售盒版式', '说明书与内托可选', '样品展示就绪'],
      specs: [
        { label: 'Box Type', value: 'Rigid box / folding carton' },
        { label: 'Artwork', value: 'Logo and color matching' },
        { label: 'Insert', value: 'Paper tray / EVA option' },
        { label: 'MOQ', value: 'By project' },
      ],
      specsZh: [
        { label: '盒型', value: '硬盒 / 折叠彩盒' },
        { label: '设计稿', value: 'Logo 与颜色匹配' },
        { label: '内托', value: '纸托 / EVA 可选' },
        { label: '起订量', value: '按项目确认' },
      ],
      moq: 'By project',
      moqZh: '按项目确认',
      leadTime: '15-25 days',
      leadTimeZh: '15-25 天',
      badge: 'OEM Support',
      badgeZh: 'OEM 支持',
    },
    {
      id: 10,
      name: 'Channel Sample Board',
      image: '/电子烟/placeholders/sample-board.svg',
      category: 'sample-packs',
      description:
        'A compact sample board for distributor teams to compare finishes, model sizes, and target shelf positioning before confirming orders.',
      descriptionZh: '紧凑样品板，帮助经销商团队在确认订单前比较表面工艺、型号尺寸和货架定位。',
      highlights: ['Mixed model presentation', 'Finish comparison', 'Useful for sales visits'],
      highlightsZh: ['混合型号展示', '表面工艺比较', '适合客户拜访'],
      specs: [
        { label: 'Pack Type', value: 'Model and finish sample' },
        { label: 'Use Case', value: 'Distributor meetings' },
        { label: 'Branding', value: 'Neutral or branded' },
        { label: 'MOQ', value: 'By inquiry' },
      ],
      specsZh: [
        { label: '套包类型', value: '型号与工艺样品' },
        { label: '使用场景', value: '经销商会议' },
        { label: '品牌方式', value: '中性或品牌化' },
        { label: '起订量', value: '询盘确认' },
      ],
      moq: 'By inquiry',
      moqZh: '询盘确认',
      leadTime: '5-9 days',
      leadTimeZh: '5-9 天',
      badge: 'Sales Tool',
      badgeZh: '销售工具',
    },
    {
      id: 11,
      name: 'ClearFlow Replacement Pod Pack',
      image: '/电子烟/placeholders/replacement-pods.svg',
      category: 'replacement-pods',
      description:
        'A replacement pod pack for repeat-purchase programs, after-sales bundles, and distributor replenishment orders.',
      descriptionZh: '替换烟弹套包，适合复购项目、售后组合和经销商补货订单。',
      highlights: ['Multi-pack cartridge format', 'Compatible program planning', 'Neutral or branded pack options'],
      highlightsZh: ['多支装烟弹形式', '支持兼容性项目规划', '中性或品牌包装可选'],
      specs: [
        { label: 'Pack Type', value: '2 pcs / 3 pcs pod pack' },
        { label: 'Capacity', value: '2 ml option' },
        { label: 'Resistance', value: '1.0 ohm / 1.2 ohm' },
        { label: 'MOQ', value: '1000 packs' },
      ],
      specsZh: [
        { label: '套包类型', value: '2 支 / 3 支装烟弹包' },
        { label: '容量', value: '2 ml 可选' },
        { label: '阻值', value: '1.0 ohm / 1.2 ohm' },
        { label: '起订量', value: '1000 包' },
      ],
      moq: '1000 packs',
      moqZh: '1000 包',
      leadTime: '10-18 days',
      leadTimeZh: '10-18 天',
      badge: 'Repeat Order',
      badgeZh: '复购补货',
    },
    {
      id: 12,
      name: 'Mesh Coil Service Pack',
      image: '/电子烟/placeholders/coil-pack.svg',
      category: 'coils-accessories',
      description:
        'A small accessory and coil service pack for distributors who need add-on replenishment items with clear SKU control.',
      descriptionZh: '雾化芯与小配件服务包，适合需要清晰 SKU 管理的经销商补充订单。',
      highlights: ['Mesh coil pack concept', 'Accessory bundle friendly', 'Simple SKU and carton planning'],
      highlightsZh: ['Mesh 雾化芯套包概念', '适合配件组合销售', '便于 SKU 和外箱规划'],
      specs: [
        { label: 'Pack Type', value: 'Coils / cable / lanyard options' },
        { label: 'Use Case', value: 'Service and replenishment' },
        { label: 'Branding', value: 'Label and carton support' },
        { label: 'MOQ', value: 'By inquiry' },
      ],
      specsZh: [
        { label: '套包类型', value: '雾化芯 / 线材 / 挂绳可选' },
        { label: '使用场景', value: '售后与补货' },
        { label: '品牌定制', value: '标签与外箱支持' },
        { label: '起订量', value: '询盘确认' },
      ],
      moq: 'By inquiry',
      moqZh: '询盘确认',
      leadTime: '7-15 days',
      leadTimeZh: '7-15 天',
      badge: 'Accessory',
      badgeZh: '配件产品',
    },
    {
      id: 13,
      name: 'Counter Display Stand',
      image: '/电子烟/placeholders/display-stand.svg',
      category: 'retail-displays',
      description:
        'A retail display support item for counter presentation, sample organization, and distributor sales visits.',
      descriptionZh: '零售陈列支持物料，适合柜台展示、样品整理和经销商销售拜访。',
      highlights: ['Counter display concept', 'Sample and shelf support', 'Useful for channel teams'],
      highlightsZh: ['柜台陈列概念', '支持样品与货架展示', '适合渠道团队使用'],
      specs: [
        { label: 'Display Type', value: 'Counter stand / sample board' },
        { label: 'Material', value: 'Paperboard / acrylic option' },
        { label: 'Branding', value: 'Logo and color support' },
        { label: 'MOQ', value: 'By project' },
      ],
      specsZh: [
        { label: '陈列类型', value: '柜台架 / 样品板' },
        { label: '材质', value: '纸板 / 亚克力可选' },
        { label: '品牌定制', value: '支持 Logo 与颜色' },
        { label: '起订量', value: '按项目确认' },
      ],
      moq: 'By project',
      moqZh: '按项目确认',
      leadTime: '15-25 days',
      leadTimeZh: '15-25 天',
      badge: 'Sales Display',
      badgeZh: '销售陈列',
    },
  ],

  servicePoints: [
    'OEM and private-label support',
    'Wholesale catalogue supply',
    'Packaging and sample coordination',
    'Email-based quotation and order follow-up',
  ],

  servicePointsZh: ['OEM 与贴牌支持', '批发目录供货', '包装与样品协调', '邮箱报价与订单跟进'],

  translations: {
    en: {
      'brand.subtitle': 'B2B Vape Catalogue',
      'nav.home': 'Home',
      'nav.products': 'Products',
      'nav.company': 'Company',
      'nav.resources': 'Resources',
      'nav.emailInquiry': 'Email Inquiry',
      'nav.open': 'Open navigation',
      'theme.system': 'System',
      'theme.light': 'Light',
      'theme.dark': 'Dark',
      'lang.en': 'EN',
      'lang.zh': '中文',
      'settings.label': 'Display settings',
      'settings.theme': 'Theme',
      'settings.language': 'Language',
      'footer.description': 'Static B2B catalogue for wholesale vape products, OEM programs, and sample inquiries.',
      'footer.productLines': 'Product Lines',
      'footer.contact': 'Contact',
      'footer.contactNote': 'Send model, quantity, market, packaging needs, and expected delivery time.',
      'footer.rights': '© 2026 BestLinksz.com. All Rights Reserved.',
      'footer.legal': 'Products intended for authorized business buyers where lawful.',
      'home.eyebrow': 'B2B Vape Product Catalogue',
      'home.title': 'BestLinksz Wholesale Vape Solutions',
      'home.heroText':
        'Static catalogue for authorized business buyers: pod systems, disposable lines, starter kits, packaging support, and email-based quotation follow-up.',
      'home.emailQuote': 'Email for Quotation',
      'home.viewProducts': 'View Products',
      'home.metric.oem': 'OEM',
      'home.metric.oemText': 'Logo, color, packaging',
      'home.metric.moq': 'MOQ',
      'home.metric.moqText': 'From 500 pcs',
      'home.metric.lead': 'Lead Time',
      'home.metric.leadText': '7-25 days',
      'home.inquiryDesk': 'Inquiry Desk',
      'home.productLines': 'Product Lines',
      'home.introTitle': 'Built for distributors, brands, and sample-driven wholesale orders.',
      'home.introText':
        'No cart, no checkout, no retail friction. Buyers review the catalogue, choose target models, and send an email inquiry for pricing, samples, packaging options, and production timing.',
      'home.featured': 'Featured Catalogue',
      'home.showcase': 'Static product showcase',
      'home.browseCategory': 'View full catalogue',
      'home.featuredText': 'One representative item from each business line. Open the catalogue page for the full range.',
      'home.howOrders': 'How Orders Start',
      'home.workflowTitle': 'Email-first wholesale workflow',
      'home.step1Title': 'Choose models',
      'home.step1Text': 'Review products and note preferred styles, quantities, target market, and packaging needs.',
      'home.step2Title': 'Send inquiry',
      'home.step2Text': 'Email the model list for price sheet, MOQ, lead time, sample availability, and OEM options.',
      'home.step3Title': 'Confirm details',
      'home.step3Text': 'Finalize specification, artwork, delivery plan, and commercial terms before production.',
      'home.wholesaleInquiry': 'Wholesale Inquiry',
      'home.contactTitle': 'Send product codes, quantity, and target market by email.',
      'home.contactEmail': 'Contact',
      'home.showSlide': 'Show',
      'common.moq': 'MOQ',
      'common.leadTime': 'Lead Time',
      'common.orderMode': 'Order Mode',
      'common.emailInquiry': 'Email Inquiry',
      'common.contact': 'Contact',
      'common.backHome': 'Back to Homepage',
      'common.backCatalogue': 'Back to Catalogue',
      'common.viewProducts': 'View Products',
      'common.wholesaleInquiry': 'Wholesale Inquiry',
      'category.directory': 'Directory',
      'category.emailPricing': 'Email for Pricing',
      'category.catalogueItems': 'Catalogue Items',
      'category.modelsAvailable': 'models available for inquiry',
      'category.helpText': 'Use the product detail page to review highlights, MOQ, lead time, and email inquiry notes.',
      'category.emptyTitle': 'No products in this category yet',
      'category.emptyTextPrefix': 'Add products in',
      'category.emptyTextSuffix': 'with category',
      'category.priceSheet': 'Need this category price sheet?',
      'category.productsFallback': 'Products',
      'catalog.eyebrow': 'Product Catalogue',
      'catalog.title': 'Explore the full B2B product directory.',
      'catalog.intro':
        'All products are grouped by business use: devices, ready lines, replacement parts, and brand support items for email-based wholesale inquiries.',
      'catalog.allProducts': 'All products',
      'catalog.jumpToCategory': 'Jump to category',
      'catalog.categories': 'categories',
      'catalog.models': 'models',
      'catalog.viewDetail': 'View detail',
      'catalog.emailPricing': 'Email for catalogue pricing',
      'product.detail': 'B2B Product Detail',
      'product.highlights': 'Key Highlights',
      'product.specification': 'Specification',
      'product.requestTitle': 'Request quotation by email',
      'product.requestText':
        'Send quantity, target market, logo/packaging needs, and sample request. No online checkout is required.',
      'product.sameCategory': 'Same Category',
      'product.related': 'Related models',
      'product.notFound': 'Product Not Found',
      'product.notFoundText': 'The product id does not exist in the catalogue data.',
      'about.eyebrow': 'Company',
      'about.title': 'Wholesale-focused vape catalogue for business buyers.',
      'about.intro':
        'BestLinksz is positioned as a static B2B product showcase. The site helps buyers quickly review product lines, then continue quotation, samples, packaging, and order details by email.',
      'about.emailInquiry': 'Email Business Inquiry',
      'about.capability1Title': 'Wholesale Catalogue',
      'about.capability1Text':
        'Clear product families, MOQ notes, lead time ranges, and category pages for distributor evaluation.',
      'about.capability2Title': 'OEM Support',
      'about.capability2Text':
        'Logo placement, color matching, packaging sleeve, user manual, and sample coordination for brand orders.',
      'about.capability3Title': 'Email Workflow',
      'about.capability3Text':
        'Orders start by email so buyer requirements, compliance labels, and delivery details can be confirmed carefully.',
      'about.orderHandling': 'Order Handling',
      'about.workflowTitle': 'Email keeps B2B requirements precise.',
      'about.workflowText':
        'Vape wholesale orders usually need target-market details, artwork confirmation, packaging notes, sample decisions, and compliance labels. A cart would hide those requirements; email makes them explicit.',
      'about.workflow1': 'Buyer sends target models, quantity, and market',
      'about.workflow2': 'Team confirms price, MOQ, sample availability, and production timing',
      'about.workflow3': 'Packaging and artwork details are reviewed before production',
      'about.workflow4': 'Order terms and delivery plan are finalized by email',
      'about.catalogueStructure': 'Catalogue Structure',
      'about.directoryTitle': 'Multi-level categories stay editable from one data file.',
      'about.contactTitle': 'Send product, sample, or OEM questions directly.',
      'blog.eyebrow': 'Resources',
      'blog.title': 'Buyer notes for faster wholesale conversations.',
      'blog.intro':
        'This page keeps the ordering process clear without adding a shopping cart. Buyers can prepare the right information before emailing for price, samples, packaging, and lead time.',
      'blog.askFiles': 'Ask for Catalogue Files',
      'blog.resource1Title': 'How to request a quotation',
      'blog.resource1Text':
        'Send model names, target quantity, market, flavor plan, packaging needs, and expected delivery time.',
      'blog.resource1Tag': 'Inquiry',
      'blog.resource2Title': 'How to compare product families',
      'blog.resource2Text':
        'Start with device type, MOQ, lead time, packaging requirement, and whether samples are needed before order confirmation.',
      'blog.resource2Tag': 'Selection',
      'blog.resource3Title': 'How OEM packaging starts',
      'blog.resource3Text':
        'Prepare logo files, preferred colors, regulatory label areas, barcode needs, and sample approval expectations.',
      'blog.resource3Tag': 'OEM',
      'blog.productDirectory': 'Product Directory',
      'blog.directoryTitle': 'Clear menu levels make catalogue browsing simple.',
      'blog.directoryText':
        'The live menu is controlled by one data file. A beginner can rename groups, add category levels, or move products by editing the catalogue data instead of touching page layout code.',
      'blog.loading': 'Loading',
      'blog.loadingTitle': 'Fast loading comes before heavy effects.',
      'blog.performance1': 'Hero image loads first; catalogue images lazy-load below the fold.',
      'blog.performance2': 'Hover animation uses lightweight transform and opacity only.',
      'blog.performance3':
        'Product images use adaptive frames so different ratios do not create hard black or white borders.',
      'notFound.title': 'Page not found',
      'notFound.text': 'The catalogue page you opened does not exist or the product id has changed.',
      'seo.homeTitle': 'BestLinksz B2B Vape Catalogue',
      'seo.homeDescription':
        'BestLinksz B2B vape product catalogue for wholesale inquiries, OEM packaging, samples, MOQ, lead time, and email-based orders.',
    },
    zh: {
      'brand.subtitle': 'B2B 电子烟目录',
      'nav.home': '首页',
      'nav.products': '产品目录',
      'nav.company': '公司能力',
      'nav.resources': '资料说明',
      'nav.emailInquiry': '邮箱询盘',
      'nav.open': '打开导航',
      'theme.system': '跟随系统',
      'theme.light': '浅色',
      'theme.dark': '深色',
      'lang.en': 'EN',
      'lang.zh': '中文',
      'settings.label': '显示设置',
      'settings.theme': '颜色模式',
      'settings.language': '语言',
      'footer.description': '面向批发电子烟产品、OEM 项目和样品询盘的静态 B2B 目录站。',
      'footer.productLines': '产品线',
      'footer.contact': '联系',
      'footer.contactNote': '请发送型号、数量、目标市场、包装需求和预计交期。',
      'footer.rights': '© 2026 BestLinksz.com. 保留所有权利。',
      'footer.legal': '产品仅面向法律允许地区的授权商业买家。',
      'home.eyebrow': 'B2B 电子烟产品目录',
      'home.title': 'BestLinksz 批发电子烟解决方案',
      'home.heroText': '面向商业买家的静态目录：换弹设备、一次性产品、套装、包装支持，以及邮箱报价跟进。',
      'home.emailQuote': '邮件询价',
      'home.viewProducts': '查看产品',
      'home.metric.oem': 'OEM',
      'home.metric.oemText': 'Logo、颜色、包装',
      'home.metric.moq': '起订量',
      'home.metric.moqText': '500 件起',
      'home.metric.lead': '交期',
      'home.metric.leadText': '7-25 天',
      'home.inquiryDesk': '询盘邮箱',
      'home.productLines': '产品线',
      'home.introTitle': '为经销商、品牌方和样品驱动的批发订单而设计。',
      'home.introText': '不做购物车、不做在线支付。买家浏览目录、选择目标型号，然后通过邮件确认价格、样品、包装和生产周期。',
      'home.featured': '精选目录',
      'home.showcase': '静态商品展示',
      'home.browseCategory': '查看完整目录',
      'home.featuredText': '每个业务大类只放一个代表款。完整型号放在产品目录页，方便客户按分类浏览。',
      'home.howOrders': '订单如何开始',
      'home.workflowTitle': '邮箱优先的批发流程',
      'home.step1Title': '选择型号',
      'home.step1Text': '浏览产品并记录款式、数量、目标市场和包装需求。',
      'home.step2Title': '发送询盘',
      'home.step2Text': '通过邮件发送型号清单，获取价格表、起订量、交期、样品和 OEM 选项。',
      'home.step3Title': '确认细节',
      'home.step3Text': '生产前确认规格、设计稿、交付计划和商业条款。',
      'home.wholesaleInquiry': '批发询盘',
      'home.contactTitle': '请通过邮件发送产品编号、数量和目标市场。',
      'home.contactEmail': '联系',
      'home.showSlide': '显示',
      'common.moq': '起订量',
      'common.leadTime': '交期',
      'common.orderMode': '订单方式',
      'common.emailInquiry': '邮箱询盘',
      'common.contact': '联系',
      'common.backHome': '返回首页',
      'common.backCatalogue': '返回目录',
      'common.viewProducts': '查看产品',
      'common.wholesaleInquiry': '批发询盘',
      'category.directory': '目录',
      'category.emailPricing': '邮件询价',
      'category.catalogueItems': '目录产品',
      'category.modelsAvailable': '个型号可询盘',
      'category.helpText': '进入详情页可查看卖点、起订量、交期和邮件询盘说明。',
      'category.emptyTitle': '该分类暂无产品',
      'category.emptyTextPrefix': '请在',
      'category.emptyTextSuffix': '中新增 category 为',
      'category.priceSheet': '需要该分类价格表？',
      'category.productsFallback': '产品目录',
      'catalog.eyebrow': '产品目录',
      'catalog.title': '浏览完整 B2B 产品目录。',
      'catalog.intro': '所有产品按业务用途分组：设备、现成系列、替换配件和品牌支持物料，适合通过邮箱发起批发询盘。',
      'catalog.allProducts': '全部产品',
      'catalog.jumpToCategory': '跳转分类',
      'catalog.categories': '个分类',
      'catalog.models': '个型号',
      'catalog.viewDetail': '查看详情',
      'catalog.emailPricing': '邮件索取目录报价',
      'product.detail': 'B2B 产品详情',
      'product.highlights': '核心卖点',
      'product.specification': '规格参数',
      'product.requestTitle': '通过邮件获取报价',
      'product.requestText': '请发送数量、目标市场、Logo/包装需求和样品请求；无需在线下单。',
      'product.sameCategory': '同分类产品',
      'product.related': '相关型号',
      'product.notFound': '未找到产品',
      'product.notFoundText': '目录数据中不存在该产品 ID。',
      'about.eyebrow': '公司能力',
      'about.title': '面向商业买家的批发型电子烟目录站。',
      'about.intro':
        'BestLinksz 定位为静态 B2B 产品展示站，帮助买家快速浏览产品线，再通过邮件继续确认报价、样品、包装和订单细节。',
      'about.emailInquiry': '发送商务询盘',
      'about.capability1Title': '批发目录',
      'about.capability1Text': '清晰的产品系列、起订量、交期范围和分类页面，方便经销商评估。',
      'about.capability2Title': 'OEM 支持',
      'about.capability2Text': '支持 Logo 位置、颜色匹配、包装套筒、说明书和品牌订单样品协调。',
      'about.capability3Title': '邮件流程',
      'about.capability3Text': '订单从邮件开始，便于确认买家需求、合规标签和交付细节。',
      'about.orderHandling': '订单处理',
      'about.workflowTitle': '邮件能让 B2B 需求更准确。',
      'about.workflowText':
        '电子烟批发订单通常需要目标市场、设计稿确认、包装说明、样品决定和合规标签。购物车会隐藏这些要求，邮件能把它们说清楚。',
      'about.workflow1': '买家发送目标型号、数量和市场',
      'about.workflow2': '团队确认价格、起订量、样品情况和生产周期',
      'about.workflow3': '生产前审核包装和设计稿细节',
      'about.workflow4': '通过邮件确认订单条款和交付计划',
      'about.catalogueStructure': '目录结构',
      'about.directoryTitle': '多级分类集中在一个数据文件里，后续好改。',
      'about.contactTitle': '产品、样品或 OEM 问题可直接邮件沟通。',
      'blog.eyebrow': '资料说明',
      'blog.title': '帮助买家更快进入批发沟通的说明页。',
      'blog.intro':
        '这个页面在不增加购物车的情况下，让订单流程更清楚。买家可以先准备关键信息，再通过邮件询问价格、样品、包装和交期。',
      'blog.askFiles': '索取目录文件',
      'blog.resource1Title': '如何请求报价',
      'blog.resource1Text': '发送型号名称、目标数量、市场、口味计划、包装需求和预计交付时间。',
      'blog.resource1Tag': '询盘',
      'blog.resource2Title': '如何比较产品系列',
      'blog.resource2Text': '先看设备类型、起订量、交期、包装要求，以及订单确认前是否需要样品。',
      'blog.resource2Tag': '选型',
      'blog.resource3Title': 'OEM 包装如何开始',
      'blog.resource3Text': '准备 Logo 文件、偏好颜色、法规标签区域、条码需求和样品确认预期。',
      'blog.resource3Tag': 'OEM',
      'blog.productDirectory': '产品目录',
      'blog.directoryTitle': '清晰的菜单层级让买家更容易浏览。',
      'blog.directoryText':
        '当前菜单由一个数据文件控制。新手可以通过修改目录数据来重命名分组、增加分类层级或移动产品，不需要改页面布局代码。',
      'blog.loading': '加载策略',
      'blog.loadingTitle': '加载速度优先于复杂动效。',
      'blog.performance1': '首页大图优先加载；折叠屏以下的目录图片懒加载。',
      'blog.performance2': '悬停动画只使用轻量 transform 和 opacity。',
      'blog.performance3': '商品图使用自适应展示框，不同比例图片不会出现生硬黑边或白边。',
      'notFound.title': '页面不存在',
      'notFound.text': '你打开的目录页面不存在，或产品 ID 已经变更。',
      'seo.homeTitle': 'BestLinksz B2B 电子烟产品目录',
      'seo.homeDescription': 'BestLinksz B2B 电子烟产品目录，支持批发询盘、OEM 包装、样品、起订量、交期和邮箱订单。',
    },
  },

  t(key) {
    return this.translations[this.language]?.[key] || this.translations.en[key] || key;
  },

  text(item, key) {
    if (!item) return '';
    const zhKey = `${key}Zh`;
    return this.language === 'zh' && item[zhKey] ? item[zhKey] : item[key];
  },

  list(item, key) {
    if (!item) return [];
    const zhKey = `${key}Zh`;
    return this.language === 'zh' && item[zhKey] ? item[zhKey] : item[key] || [];
  },

  get localizedServicePoints() {
    return this.language === 'zh' ? this.servicePointsZh : this.servicePoints;
  },

  getProduct(id) {
    return this.products.find((product) => product.id === parseInt(id));
  },

  getProductsByCategory(categoryId) {
    return this.products.filter((product) => product.category === categoryId);
  },

  getCategory(categoryId) {
    return this.categories.find((category) => category.id === categoryId);
  },

  getCategoryGroup(categoryId) {
    return this.categoryGroups.find((group) => group.children.some((child) => child.id === categoryId));
  },
});
